name: SWU Clinic App 

on: 
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript and bundle assets
        run: npm run build